### ISSUE TITLE
Ubuntu/Linux Support.

### ISSUE THREAD

**Issue by jonathan148** [DigiExam/simplewifi#17]
Will there be any Ubuntu/Linux support?

If no, Can I fix it somehow?

Greetings, Me.

**Comment by robinwassen** [comment]
Hi @jonathan148 

I have no plans on building support for linux, the code design is not prepared for cross platform support either.

In order to build support for linux you would first have to research on how to handle wifi connections programmatically, then implement the whole thing in the library, so it is not simply a small change.

Seems like nl80211 is used for managing wifi on modern linux builds: http://stackoverflow.com/questions/5102186/wireless-api-for-linux-in-c-or-java

Regards,
Robin
